"""api key last used

Revision ID: 0dfa3ff7c781
Revises: 725f95b1886f
Create Date: 2021-07-27 16:35:24.817995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfa3ff7c781'
down_revision = '725f95b1886f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('last_used', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'last_used')
    # ### end Alembic commands ###
