"""empty message

Revision ID: 49934e70c227
Revises: 9f49bc310828
Create Date: 2019-09-11 14:56:51.856475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49934e70c227'
down_revision = '9f49bc310828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group', 'admin', server_default='0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group', 'admin', server_default=None)
    # ### end Alembic commands ###
