"""token description

Revision ID: 725f95b1886f
Revises: 89ba708d5a5f
Create Date: 2021-07-24 15:33:40.257102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725f95b1886f'
down_revision = 'd6aadc635f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'description')
    # ### end Alembic commands ###
