"""table_mapping_removed_extra_columns

Revision ID: 89ba708d5a5f
Revises: c3cad977ea45
Create Date: 2022-04-08 15:33:38.238833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ba708d5a5f'
down_revision = 'c3cad977ea45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_table', 'contact_name')
    op.drop_column('service_table', 'contact_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_table', sa.Column('contact_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('service_table', sa.Column('contact_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
