"""added affiliation contact

Revision ID: a489357589a6
Revises: bac73e243b14
Create Date: 2022-03-16 17:25:01.531262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a489357589a6'
down_revision = 'bac73e243b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliation', sa.Column('contact_name', sa.String(length=120), nullable=True))
    op.add_column('affiliation', sa.Column('contact_email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliation', 'contact_email')
    op.drop_column('affiliation', 'contact_name')
    # ### end Alembic commands ###
