"""Renamed Association to Affiliation

Revision ID: bac73e243b14
Revises: 120f11f4d018
Create Date: 2022-03-16 16:03:15.875031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bac73e243b14'
down_revision = '120f11f4d018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_association', 'association_id', nullable=False, new_column_name='affiliation_id')
    op.rename_table('association', 'affiliation')
    op.rename_table('user_association', 'user_affiliation')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('affiliation', 'association')
    op.rename_table('user_affiliation', 'user_association')
    op.alter_column('user_association', 'affiliation_id', nullable=False, new_column_name='association_id')
    # ### end Alembic commands ###
