"""api key

Revision ID: d6aadc635f00
Revises: 795501136c51
Create Date: 2021-07-22 16:33:21.047055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aadc635f00'
down_revision = '795501136c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('api_key', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('api_key_user_id_key', 'api_key', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('api_key_user_id_key', 'api_key', ['user_id'])
    op.drop_column('api_key', 'updated')
    op.drop_column('api_key', 'created')
    # ### end Alembic commands ###
